services:
  - type: worker
    name: cv-bot
    env: python
    pythonVersion: "3.11.0"
    numInstances: 1
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SHOP_LINK
        sync: false
